import React from 'react';
import type { MedicationInfo } from '../types';
import { PillIcon } from './icons';

interface MedicationReportProps {
  info: MedicationInfo;
}

const MedicationReport: React.FC<MedicationReportProps> = ({ info }) => {
  return (
    <div className="w-full max-w-2xl mx-auto bg-white/70 backdrop-blur-sm p-6 sm:p-8 rounded-2xl shadow-lg border border-slate-200 mt-8 space-y-6">
      
      <div className="p-6 rounded-lg bg-green-50/50">
        <div className="flex items-center gap-3">
            <PillIcon className="w-8 h-8 text-green-600" />
            <div>
                <h2 className="text-sm font-semibold text-slate-600 uppercase tracking-wider">Medicine Identified</h2>
                <p className="text-3xl font-bold text-green-700 mt-1">{info.medicine_name}</p>
            </div>
        </div>
      </div>

      <div className="space-y-4">
        <div>
          <h3 className="text-sm font-semibold text-slate-600 uppercase tracking-wider">Usage</h3>
          <p className="text-lg text-slate-800 mt-1">{info.usage}</p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-slate-50 p-4 rounded-lg">
                <h3 className="text-sm font-semibold text-slate-600 uppercase tracking-wider">Dosage</h3>
                <p className="text-lg font-bold text-slate-800 mt-1">{info.dosage}</p>
            </div>
            <div className="bg-slate-50 p-4 rounded-lg">
                <h3 className="text-sm font-semibold text-slate-600 uppercase tracking-wider">Schedule</h3>
                <p className="text-lg font-bold text-slate-800 mt-1">{info.schedule}</p>
            </div>
        </div>
      </div>
        
      {info.reminders && info.reminders.length > 0 && (
        <div className="bg-amber-50 p-4 rounded-lg">
          <h3 className="text-sm font-semibold text-amber-800 uppercase tracking-wider">Friendly Reminders (Hinglish)</h3>
          <ul className="list-disc list-inside mt-2 text-amber-900 font-medium space-y-1">
            {info.reminders.map((reminder, index) => <li key={index}>{reminder}</li>)}
          </ul>
        </div>
      )}

       <div className="text-center text-xs text-slate-500 pt-4">
        <p>Disclaimer: This information is generated by AI based on the provided photo. Always confirm with a doctor or pharmacist before taking any medication.</p>
      </div>

    </div>
  );
};

export default MedicationReport;